#!/bin/bash
baseDir=$(pwd)

rm -r ~/.vim && ln -s $baseDir/vim ~/.vim
rm ~/.bashrc && ln -s $baseDir/bashrc  ~/.bashrc
rm ~/.vimrc && ln -s $baseDir/vimrc ~/.vimrc
rm -r ~/bin && ln -s $baseDir/bin ~/bin
rm -r ~/.font && ln -s $baseDir/fonts ~/.fonts

fc-cache -vf
source ~/.bashrc
