#!/bin/bash
baseDir=$(pwd)
rm -rf ~/.vim && ln -s $baseDir/vim ~/.vim
rm ~/.bashrc && ln -s $baseDir/bashrc  ~/.bashrc
rm -rf ~/.vimrc && ln -s $baseDir/vimrc ~/.vimrc
rm -rf ~/bin && ln -s $baseDir/bin ~/bin
